//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AthenticationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Eid { get; set; }
        public string Ename { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public int Depid { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
